[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "9.1.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
